-- MySQL Script generated by MySQL Workbench
-- 11/17/15 10:44:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Restaurant
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Restaurant
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Restaurant` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Restaurant` ;

-- -----------------------------------------------------
-- Table `Restaurant`.`PLATOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurant`.`PLATOS` (
  `idPLATOS` INT NOT NULL COMMENT '',
  `Nombre` VARCHAR(45) NULL COMMENT '',
  `Tipo` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idPLATOS`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurant`.`TRABAJADORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurant`.`TRABAJADORES` (
  `DNI` INT NOT NULL COMMENT '',
  `Apellido` VARCHAR(45) NULL COMMENT '',
  `Nombre` VARCHAR(45) NULL COMMENT '',
  `NsegSoc` INT NULL COMMENT '',
  `Telefono` INT NULL COMMENT '',
  `TelMovil` INT NULL COMMENT '',
  PRIMARY KEY (`DNI`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurant`.`COCINERO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurant`.`COCINERO` (
  `AnioServ` INT NULL COMMENT '',
  `DNI` INT NOT NULL COMMENT '',
  PRIMARY KEY (`DNI`)  COMMENT '',
  CONSTRAINT `fk_COCINERO_TRABAJADORES`
    FOREIGN KEY (`DNI`)
    REFERENCES `Restaurant`.`TRABAJADORES` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurant`.`AYUDANTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurant`.`AYUDANTE` (
  `FechaNac` DATE NULL COMMENT '',
  `DNI` INT NOT NULL COMMENT '',
  `ENCARGADO` INT NOT NULL COMMENT '',
  PRIMARY KEY (`DNI`, `ENCARGADO`)  COMMENT '',
  INDEX `fk_AYUDANTE_COCINERO1_idx` (`ENCARGADO` ASC)  COMMENT '',
  CONSTRAINT `fk_AYUDANTE_TRABAJADORES1`
    FOREIGN KEY (`DNI`)
    REFERENCES `Restaurant`.`TRABAJADORES` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AYUDANTE_COCINERO1`
    FOREIGN KEY (`ENCARGADO`)
    REFERENCES `Restaurant`.`COCINERO` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurant`.`INGREDIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurant`.`INGREDIENTE` (
  `IdIng` INT NOT NULL COMMENT '',
  `Nombre` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`IdIng`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurant`.`PREPARA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurant`.`PREPARA` (
  `DNI` INT NOT NULL COMMENT '',
  `idPLATOS` INT NOT NULL COMMENT '',
  PRIMARY KEY (`DNI`, `idPLATOS`)  COMMENT '',
  INDEX `fk_COCINERO_has_PLATOS_PLATOS1_idx` (`idPLATOS` ASC)  COMMENT '',
  INDEX `fk_COCINERO_has_PLATOS_COCINERO1_idx` (`DNI` ASC)  COMMENT '',
  CONSTRAINT `fk_COCINERO_has_PLATOS_COCINERO1`
    FOREIGN KEY (`DNI`)
    REFERENCES `Restaurant`.`COCINERO` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COCINERO_has_PLATOS_PLATOS1`
    FOREIGN KEY (`idPLATOS`)
    REFERENCES `Restaurant`.`PLATOS` (`idPLATOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurant`.`USA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurant`.`USA` (
  `idPLATOS` INT NOT NULL COMMENT '',
  `IdIng` INT NOT NULL COMMENT '',
  `Cantidad` INT NULL COMMENT '',
  PRIMARY KEY (`idPLATOS`, `IdIng`)  COMMENT '',
  INDEX `fk_PLATOS_has_INGREDIENTE_INGREDIENTE1_idx` (`IdIng` ASC)  COMMENT '',
  INDEX `fk_PLATOS_has_INGREDIENTE_PLATOS1_idx` (`idPLATOS` ASC)  COMMENT '',
  CONSTRAINT `fk_PLATOS_has_INGREDIENTE_PLATOS1`
    FOREIGN KEY (`idPLATOS`)
    REFERENCES `Restaurant`.`PLATOS` (`idPLATOS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PLATOS_has_INGREDIENTE_INGREDIENTE1`
    FOREIGN KEY (`IdIng`)
    REFERENCES `Restaurant`.`INGREDIENTE` (`IdIng`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurant`.`ALMACEN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurant`.`ALMACEN` (
  `idALMACEN` INT NOT NULL COMMENT '',
  `Nombre` VARCHAR(45) NULL COMMENT '',
  `Decripcion` VARCHAR(45) NULL COMMENT '',
  `Direccion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`idALMACEN`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurant`.`ESTANTERIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurant`.`ESTANTERIA` (
  `idEST` INT NOT NULL COMMENT '',
  `Letra` CHAR NULL COMMENT '',
  `Tamanio` INT NULL COMMENT '',
  `idALMACEN` INT NOT NULL COMMENT '',
  PRIMARY KEY (`idEST`)  COMMENT '',
  INDEX `fk_ESTANTERIA_ALMACEN1_idx` (`idALMACEN` ASC)  COMMENT '',
  CONSTRAINT `fk_ESTANTERIA_ALMACEN1`
    FOREIGN KEY (`idALMACEN`)
    REFERENCES `Restaurant`.`ALMACEN` (`idALMACEN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Restaurant`.`ALMACENA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Restaurant`.`ALMACENA` (
  `IdIng` INT NOT NULL COMMENT '',
  `idEST` INT NOT NULL COMMENT '',
  `Cantidad` INT NULL COMMENT '',
  PRIMARY KEY (`IdIng`, `idEST`)  COMMENT '',
  INDEX `fk_INGREDIENTE_has_ESTANTERIA_ESTANTERIA1_idx` (`idEST` ASC)  COMMENT '',
  INDEX `fk_INGREDIENTE_has_ESTANTERIA_INGREDIENTE1_idx` (`IdIng` ASC)  COMMENT '',
  CONSTRAINT `fk_INGREDIENTE_has_ESTANTERIA_INGREDIENTE1`
    FOREIGN KEY (`IdIng`)
    REFERENCES `Restaurant`.`INGREDIENTE` (`IdIng`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_INGREDIENTE_has_ESTANTERIA_ESTANTERIA1`
    FOREIGN KEY (`idEST`)
    REFERENCES `Restaurant`.`ESTANTERIA` (`idEST`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
